CREATE TABLE wishList (
    itemNO NUMBER,
    buyerId NUMBER,

    CONSTRAINT fk_wl_buyer FOREIGN KEY (buyerId) REFERENCES userTable(userID),
    CONSTRAINT fk_wl_item FOREIGN KEY (itemNO) REFERENCES item(itemNO)
);
drop table wishList;
INSERT ALL
    INTO WISHLIST (ITEMNO, BUYERID) VALUES (9, 219)
    INTO WISHLIST (ITEMNO, BUYERID) VALUES (8, 7)
    INTO WISHLIST (ITEMNO, BUYERID) VALUES (4, 3)
    INTO WISHLIST (ITEMNO, BUYERID) VALUES (11, 10)
    INTO WISHLIST (ITEMNO, BUYERID) VALUES (4, 123)
SELECT * FROM dual;

SELECT * from WISHLIST;